### PR TITLE
Introduce preserve_hour_of_day

### LINKED ISSUE #202: Allow to specify preserve_hour_of_day.
As of now, btrbk always tries to save the midnight snapshots for the daily backups.

I run hourly snapshots and I am also often working late after midnight, so I would like my work to be saved at a configurable hour for my daily snapshots. For example at 0600 hours and not at midnight. 
btrbk would then try to preserve the next closest snapshot to 0600 hours for the daily snapshots.

This is important for me because I often have very large files (disk images) open, some are only temporary, that I have uncompressed while working and compressed while not working. If btrbk preserves the snapshots at midnight, when I am working on these and they are large, it wastes a lot of space in the backups even with dedup and file-system level compression.

### PR DESCRIPTION
**Pull request by Thiodwitnir**
Introduces the new config option "preserve_hour_of_day" to specify after what time backups should be considered as dailies.

Resolves #202

### CODE REVIEW

**Comment by digint** [comment]
Thanks for contributing!
The patch looks fine, I'll have to do some corner-case tests before merging though. This could take a couple of days as I'm very busy at the moment...

**Comment by digint** [comment]
I reviewed your pull request, and (besides some cosmetics) I also had to fix the calculation of weekly backups:

https://github.com/digint/btrbk/commit/5a00dae667e283750a14f3cfbd8a00681acd7b1c#diff-5fad842a60ed39ebd6f98b9b5b556cf9R3737

without this, btrbk would pick the first snapshot/backup at `preserve_day_of_week` as weekly even if it was created before `preserve_hour_of_day`.

Please review / test / comment the [preserve_hour_of_day branch](/digint/btrbk/tree/preserve_hour_of_day).

Note that I also changed the text output to be easier to read in commits e6da71f68602b28e7b4efa42324491c9597a9c7c and 9610ab19e802be843ca906b4e6e4a9bb100eb169

**Comment by digint** [comment]
merged to master in 5791d7217177df888e071f8c361b32e9601af8c0

**Comment by DL6AKU** [comment]
Thank you very much!

**Pull request closed without merging**
