### PR TITLE
more solid and flexible way to run scheduled tasks

### PR DESCRIPTION
**Pull request by ceremcem**

### CODE REVIEW

**Comment by digint** [comment]
Not sure about that one. I try to be very simple / straight forward in the README.

So people who are not linux experts can simply add a straight-forward script to /etc/cron.daily (which I think exists on most distros), and for the linux experts, well, they will do it their way anyway.

**Comment by ceremcem** [comment]
In fact I had a problem with it :) 

I located the script at `/etc/cron.hourly/btrbk` and `chmod +x /etc/cron.hourly/btrbk`; it still refused to run. My last resort was adding it to `/etc/crontab`, but locating the configuration in `/etc/cron.d` seemed cleaner way to go.

**Comment by ian-kelling** [comment]
If I remember right, some distros are not setup to run cron.hourly. Does your /etc/crontab contain the line

```
17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
```
?

I agree with digint. He gave a very simple example, and you adapted it to your needs, so it worked. Also, your pull request does hourly, but the text says daily, and you have "*/1", which I think could be simplified to simply "*". Nowadays, I've been using systemd timers, so for someone like me, or using some other method, the esoteric cron syntax is just a distraction.

**Comment by ceremcem** [comment]
Yes, `run-parts` seemed to run `/etc/cron.hourly`: 

```
grep hourly /etc/crontab 
17 *	* * *	root    cd / && run-parts --report /etc/cron.hourly
```

OK, if we think that "everyone may find their own way to schedule a script in his/her system", I'm closing this PR (in a few days, if no respond)

**Pull request closed without merging**
