### PR TITLE
Makefile: Skip temporary file

### PR DESCRIPTION
**Pull request by aude**
This makes the makefile more readable in my opinion.

### CODE REVIEW

**Comment by aude** [comment]
Ref. https://github.com/digint/btrbk/pull/93#issuecomment-229508433.

**Comment by digint** [comment]
I've had a look at it, seems to work fine.

But for some reasons I can't find any documentation of this feature, neither in install(1) nor in the info pages or [official docs](https://www.gnu.org/software/coreutils/install).

This makes me hesitate a bit, as package builders might use ancient coreutils versions and I can't make sure that this will work on all versions of coreutils.

Do you have a link to any documentation regarding this?

**Comment by aude** [comment]
Had to look to find documentation for this feature. I was pretty sure it's a Linux feature, but not certain.

Anyway, here's a pretty complete answer: https://unix.stackexchange.com/questions/36403/how-portable-are-dev-stdin-dev-stdout-and-dev-stderr

What are your thoughts after reading that?

**Comment by digint** [comment]
Still unsure. Using temp files is a common way for these things, and there's no real need to merge this (or is there?). I'm very afraid of opening pandoras box with this...

**Comment by aude** [comment]
No, there's no real need. Thanks for staying critical, I believe it contributes to make your software as robust as it is. Let's not open that pandoras box.

**Pull request closed without merging**
