### PR TITLE
add script for restoring raw backups

### PR DESCRIPTION
**Pull request by fr3aker**
Adds a basic python script to restore incremental raw backups into a btrfs subvolume.

The implementation status of this script is mostly "works for me". pbkdf2 and gpg options are not supported. Mileage for (de)compressors may vary. It should be easy enough to extend if anyone needs the missing features.

usage:

    btrbk_restore_raw.py -h
    usage: btrbk_restore_raw.py [-h] [--ignore-missing] [--openssl-keyfile OPENSSL_KEYFILE] backup btrfs_subvol
    
    restore btrbk raw backup
    
    positional arguments:
      backup                backup file to restore; for incrementalbackups the parent files must be in the same directory
      btrfs_subvol          btrfs subvolume to restore snapshots to using btrfs receive
    
    optional arguments:
      -h, --help            show this help message and exit
      --ignore-missing      do not fail on missing parent snapshots
      --openssl-keyfile OPENSSL_KEYFILE
                            path to private encryption key file

example run with success:

    # btrbk_restore_raw.py /mnt/backups/ROOT.20210709.btrfs.xz.encrypted /test --openssl-keyfile /etc/btrbk/openssl_enc.key
    2021-07-09 20:58:18,215 INFO - restoring backup ROOT.20210708.btrfs.xz.encrypted
    2021-07-09 20:59:54,994 INFO - restoring backup ROOT.20210709.btrfs.xz.encrypted
    2021-07-09 20:59:57,229 INFO - finished; restored 2 backup files

example run with error:
    
    # btrbk_restore_raw.py /mnt/backups/ROOT.20210709.btrfs.xz.encrypted /test --openssl-keyfile /etc/btrbk/openssl_enc.key
    2021-07-09 21:03:50,464 INFO - restoring backup ROOT.20210708.btrfs.xz.encrypted
    2021-07-09 21:03:52,571 ERROR - error running ['btrfs', 'receive', '/test']: At subvol ROOT.20210708
    ERROR: creating subvolume ROOT.20210708 failed: File exists
    2021-07-09 21:03:52,571 INFO - restoring backup ROOT.20210709.btrfs.xz.encrypted
    2021-07-09 21:03:54,582 ERROR - error running ['btrfs', 'receive', '/test']: ERROR: creating snapshot test/ROOT.20210708 -> ROOT.20210709 failed: File exists
    2021-07-09 21:03:54,582 INFO - finished; restored 2 backup files

### CODE REVIEW

**Comment by digint** [comment]
Thanks for contributing!

I finally got around to test this a bit, works for me as well.

Pushed some tiny fixups (will squash them on final merge).

I'd love to see a `-n, --dryrun` option, dumping the commands that will be executed. Would that be possible / not too complicated? Point is that it makes me very nervous when running scripts like this as root, without being able to double-check what will happen.

**Comment by fr3aker** [comment]
Thank you for the review and fixes! It should require reasonable effort to add a dry run option. I'll look into it.

**Comment by fr3aker** [comment]
Added the dry run mode. The output contains a small lie: in order to have the file name easily visible it introduces an artificial "cat {file}" as the first command in the pipeline. In reality it simply passes on the file handle to stdin.

**Comment by digint** [comment]
Great, thanks.

Again added some cosmetics. Unless you yell I'll merge this (squashed) for next release (soon)

**Comment by fr3aker** [comment]
looks good to me, thanks for checking!

**Comment by digint** [comment]
merged in: 82860f0f4c413cb73928bf434e0c983cd7a6dd7a, bddd7a1d69ce2ed70cfc6b1c68560393be49ae67

now eagerly waiting for my disks doing raw backups to finally fail :D

**Pull request closed without merging**
